# Generated by Django 3.1 on 2020-11-12 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rClass',
        ),
    ]
